spring.application.name=travel-assistant
server.port=8080

openai.api.key=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
weather.api.key=320125b097fa4466a61131924261005

resilience4j.retry.instances.openAiApi.max-attempts=3
resilience4j.retry.instances.openAiApi.wait-duration=1s

resilience4j.retry.instances.weatherApi.max-attempts=3
resilience4j.retry.instances.weatherApi.wait-duration=1s

resilience4j.circuitbreaker.instances.openAiApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.openAiApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.openAiApi.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.weatherApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.weatherApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.weatherApi.wait-duration-in-open-state=10s