spring.application.name=travel-assistant
server.port=8080

geoapify.api.key=${GEOAPIFY_API_KEY:dummy-geoapify-key}
weather.api.key=${WEATHER_API_KEY:dummy-weather-key}

resilience4j.retry.instances.weatherApi.max-attempts=3
resilience4j.retry.instances.weatherApi.wait-duration=1s

resilience4j.retry.instances.activitiesApi.max-attempts=3
resilience4j.retry.instances.activitiesApi.wait-duration=1s

resilience4j.circuitbreaker.instances.weatherApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.weatherApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.weatherApi.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.activitiesApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.activitiesApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.activitiesApi.wait-duration-in-open-state=10s